In [1]:
import pandas as pd

In [2]:
#Take the table of 2020 stats from pro football reference. Has season long stats all in one table
rb2020url = 'https://www.pro-football-reference.com/years/2020/rushing.htm'
list_of_df = pd.read_html(rb2020url)

In [3]:
#Set the df
rb2020 = list_of_df[0]

In [4]:
#Let's get rid of the hierarchy making a mess
rb2020.columns = rb2020.columns.droplevel(0)

In [5]:
#This dataframe looks good. We need to clean up names and remove players that have rushing stats but aren't positions
#We want. So we need to look at the Position column
rb2020

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
0,1,Derrick Henry *+,TEN,26,RB,16,16,378,2027,17,98,94,5.4,126.7,3
1,2,Dalvin Cook*,MIN,25,RB,14,14,312,1557,16,91,70,5.0,111.2,5
2,3,Josh Jacobs*,LVR,22,RB,15,15,273,1065,12,61,28,3.9,71.0,2
3,4,David Montgomery,CHI,23,RB,15,14,247,1070,8,59,80,4.3,71.3,1
4,5,Ezekiel Elliott,DAL,25,RB,15,15,244,979,6,62,31,4.0,65.3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,368,Jonathan Williams,DET,26,NaN,5,0,1,5,0,0,5,5.0,1.0,1
380,369,Mike Williams,LAC,26,WR,15,11,1,1,0,0,1,1.0,0.1,0
381,370,Javon Wims,CHI,26,wr,13,1,1,2,0,0,2,2.0,0.2,0
382,371,Olamide Zaccheaus,ATL,23,wr,11,2,1,0,0,0,0,0.0,0.0,0
383,372,Brandon Zylstra,CAR,27,wr,16,2,1,1,0,0,1,1.0,0.1,0

In [6]:
#So we have lots of issues. Capitalization, and a ton of missing values. Lets fix capitalization first to combine these
rb2020.Pos.value_counts()

wr     56
rb     55
WR     32
qb     32
QB     25
RB     21
Pos    12
te      7
fb      6
p       5
TE      5
FB      2
fs      2
C       1
olb     1
FS      1
ss      1
mlb     1
cb      1
Name: Pos, dtype: int64

In [7]:
#Make everything uppercase
rb2020.Pos = rb2020.Pos.str.upper()

In [8]:
#Now we have our positions. We will remove the stuff we don't want... when we have all the people's positions listed
rb2020.Pos.value_counts()

WR     88
RB     76
QB     57
POS    12
TE     12
FB      8
P       5
FS      3
OLB     1
MLB     1
SS      1
CB      1
C       1
Name: Pos, dtype: int64

In [9]:
#We have 118 missing values in the position column. For completeness, I will fill in their positions manually below
#But we also could have set a threshold that people needed 5 carries in a season to be added. This should remove a
#lot of the defensive players and punters, but this will work
rb2020.isnull().sum()

Rk          0
Player      0
Tm          0
Age         0
Pos       118
G           0
GS          0
Att         0
Yds         0
TD          0
1D          0
Lng         0
Y/A         0
Y/G         0
Fmb         0
dtype: int64

In [10]:
#Here are the people with missing positions. Lots of rookies, punt returners or random missing people
rb2020[rb2020.Pos.isnull()]

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
44,44,Zack Moss,BUF,23,NaN,13,0,112,481,4,30,31,4.3,37.0,0
45,45,Joshua Kelley,LAC,23,NaN,14,0,111,354,2,20,33,3.2,25.3,2
49,49,Malcolm Brown,LAR,27,NaN,16,0,101,419,5,25,19,4.1,26.2,1
57,57,Kalen Ballage,2TM,25,NaN,11,2,91,303,3,25,17,3.3,27.5,1
63,62,Jordan Wilkins,IND,26,NaN,15,0,84,308,1,17,22,3.7,20.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,354,Mohamed Sanu,2TM,31,NaN,10,4,1,3,0,1,3,3.0,0.3,0
371,360,Easton Stick,LAC,25,NaN,1,0,1,-2,0,0,-2,-2.0,-2.0,0
374,363,Mike Thomas,CIN,26,NaN,14,0,1,1,0,0,1,1.0,0.1,1
376,365,Austin Walter,SFO,24,NaN,4,0,1,3,0,0,3,3.0,0.8,0
379,368,Jonathan Williams,DET,26,NaN,5,0,1,5,0,0,5,5.0,1.0,1

In [11]:
#Time to manually fill them in. Hope I don't mess them up. I'm 99% sure there was an easier way to both write this out
#And to gather the information. Oh well

rb2020.Pos[44] = 'RB'
rb2020.Pos[45] = 'RB'
rb2020.Pos[49] = 'RB'
rb2020.Pos[57] = 'RB'
rb2020.Pos[63] = 'RB'
rb2020.Pos[65] = 'RB'
rb2020.Pos[72] = 'RB'
rb2020.Pos[73] = 'RB'
rb2020.Pos[76] = 'RB'
rb2020.Pos[79] = 'RB'
rb2020.Pos[85] = 'RB'
rb2020.Pos[86] = 'RB'
rb2020.Pos[87] = 'RB'
rb2020.Pos[94] = 'RB'
rb2020.Pos[95] = 'RB'
rb2020.Pos[101] = 'RB'
rb2020.Pos[102] = 'RB'
rb2020.Pos[107] = 'RB'
rb2020.Pos[108] = 'RB'
rb2020.Pos[109] = 'RB'
rb2020.Pos[111] = 'RB'
rb2020.Pos[112] = 'RB'
rb2020.Pos[116] = 'RB'
rb2020.Pos[119] = 'RB'
rb2020.Pos[120] = 'RB'
rb2020.Pos[128] = 'RB'
rb2020.Pos[129] = 'RB'
rb2020.Pos[130] = 'RB'
rb2020.Pos[133] = 'RB'
rb2020.Pos[134] = 'RB'
rb2020.Pos[135] = 'RB'
rb2020.Pos[136] = 'RB'
rb2020.Pos[141] = 'RB'
rb2020.Pos[145] = 'QB'
rb2020.Pos[148] = 'RB'
rb2020.Pos[149] = 'RB'
rb2020.Pos[150] = 'RB'
rb2020.Pos[151] = 'RB'
rb2020.Pos[154] = 'QB'
rb2020.Pos[155] = 'RB'
rb2020.Pos[157] = 'RB'
rb2020.Pos[158] = 'RB'
rb2020.Pos[159] = 'QB'
rb2020.Pos[160] = 'RB'
rb2020.Pos[161] = 'RB'
rb2020.Pos[162] = 'RB'
rb2020.Pos[164] = 'RB'
rb2020.Pos[165] = 'RB'
rb2020.Pos[168] = 'QB'
rb2020.Pos[170] = 'RB'
rb2020.Pos[172] = 'RB'
rb2020.Pos[174] = 'RB'
rb2020.Pos[176] = 'QB'
rb2020.Pos[178] = 'RB'
rb2020.Pos[179] = 'QB'
rb2020.Pos[185] = 'RB'
rb2020.Pos[188] = 'RB'
rb2020.Pos[189] = 'QB'
rb2020.Pos[192] = 'RB'
rb2020.Pos[195] = 'QB'
rb2020.Pos[196] = 'RB'
rb2020.Pos[197] = 'QB'
rb2020.Pos[201] = 'QB'
rb2020.Pos[209] = 'WR'
rb2020.Pos[211] = 'RB'
rb2020.Pos[212] = 'RB'
rb2020.Pos[213] = 'RB'
rb2020.Pos[214] = 'RB'
rb2020.Pos[223] = 'RB'
rb2020.Pos[224] = 'QB'
rb2020.Pos[226] = 'WR'
rb2020.Pos[232] = 'RB'
rb2020.Pos[242] = 'QB'
rb2020.Pos[243] = 'QB'
rb2020.Pos[248] = 'RB'
rb2020.Pos[251] = 'RB'
rb2020.Pos[254] = 'WR'
rb2020.Pos[256] = 'TE'
rb2020.Pos[258] = 'RB'
rb2020.Pos[261] = 'QB'
rb2020.Pos[263] = 'WR'
rb2020.Pos[266] = 'RB'
rb2020.Pos[273] = 'QB'
rb2020.Pos[274] = 'QB'
rb2020.Pos[275] = 'WR'
rb2020.Pos[278] = 'S'
rb2020.Pos[279] = 'RB'
rb2020.Pos[283] = 'S'
rb2020.Pos[284] = 'WR'
rb2020.Pos[289] = 'WR'
rb2020.Pos[295] = 'RB'
rb2020.Pos[296] = 'RB'
rb2020.Pos[299] = 'QB'
rb2020.Pos[301] = 'QB'
rb2020.Pos[303] = 'RB'
rb2020.Pos[304] = 'S'
rb2020.Pos[305] = 'WR'
rb2020.Pos[311] = 'FB'
rb2020.Pos[312] = 'QB'
rb2020.Pos[326] = 'WR'
rb2020.Pos[327] = 'WR'
rb2020.Pos[328] = 'WR'
rb2020.Pos[340] = 'WR'
rb2020.Pos[342] = 'RB'
rb2020.Pos[346] = 'WR'
rb2020.Pos[349] = 'WR'
rb2020.Pos[350] = 'S'
rb2020.Pos[351] = 'WR'
rb2020.Pos[353] = 'RB'
rb2020.Pos[354] = 'RB'
rb2020.Pos[356] = 'QB'
rb2020.Pos[358] = 'RB'
rb2020.Pos[361] = 'WR'
rb2020.Pos[364] = 'WR'
rb2020.Pos[371] = 'QB'
rb2020.Pos[374] = 'WR'
rb2020.Pos[376] = 'RB'
rb2020.Pos[379] = 'RB'

In [12]:
#We should have nothing missing now
rb2020.isnull().sum()

Rk        0
Player    0
Tm        0
Age       0
Pos       0
G         0
GS        0
Att       0
Yds       0
TD        0
1D        0
Lng       0
Y/A       0
Y/G       0
Fmb       0
dtype: int64

In [13]:
#Now let's only include RBs, WRs, TEs and FBs. Everything else is unneeded.
rb2020.Pos.value_counts()

RB     149
WR     106
QB      78
TE      13
POS     12
FB       9
P        5
S        4
FS       3
OLB      1
MLB      1
SS       1
CB       1
C        1
Name: Pos, dtype: int64

In [14]:
rb2020 = rb2020.loc[rb2020.Pos.isin(['RB', 'WR', 'TE', 'FB'])]

In [15]:
rb2020

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
0,1,Derrick Henry *+,TEN,26,RB,16,16,378,2027,17,98,94,5.4,126.7,3
1,2,Dalvin Cook*,MIN,25,RB,14,14,312,1557,16,91,70,5.0,111.2,5
2,3,Josh Jacobs*,LVR,22,RB,15,15,273,1065,12,61,28,3.9,71.0,2
3,4,David Montgomery,CHI,23,RB,15,14,247,1070,8,59,80,4.3,71.3,1
4,5,Ezekiel Elliott,DAL,25,RB,15,15,244,979,6,62,31,4.0,65.3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,368,Jonathan Williams,DET,26,RB,5,0,1,5,0,0,5,5.0,1.0,1
380,369,Mike Williams,LAC,26,WR,15,11,1,1,0,0,1,1.0,0.1,0
381,370,Javon Wims,CHI,26,WR,13,1,1,2,0,0,2,2.0,0.2,0
382,371,Olamide Zaccheaus,ATL,23,WR,11,2,1,0,0,0,0,0.0,0.0,0
383,372,Brandon Zylstra,CAR,27,WR,16,2,1,1,0,0,1,1.0,0.1,0

In [16]:
wr2020url = 'https://www.pro-football-reference.com/years/2020/receiving.htm'
dfs = pd.read_html(wr2020url)
wr2020 = dfs[0]

In [17]:
#Once again we need to clean up names and position and remove people who caught passes we don't care about
wr2020

,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Ctch%,Yds,Y/R,TD,1D,Lng,Y/Tgt,R/G,Y/G,Fmb
0,1,Stefon Diggs*+,BUF,27,WR,16,15,166,127,76.5%,1535,12.1,8,73,55,9.2,7.9,95.9,0
1,2,Davante Adams*+,GNB,28,WR,14,14,149,115,77.2%,1374,11.9,18,73,56,9.2,8.2,98.1,1
2,3,DeAndre Hopkins*,ARI,28,WR,16,16,160,115,71.9%,1407,12.2,6,75,60,8.8,7.2,87.9,3
3,4,Darren Waller*,LVR,28,TE,16,15,145,107,73.8%,1196,11.2,9,69,38,8.2,6.7,74.8,2
4,5,Travis Kelce*+,KAN,31,TE,15,15,145,105,72.4%,1416,13.5,11,79,45,9.8,7.0,94.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,495,Trevon Wesco,NYJ,25,te,12,4,2,1,50.0%,5,5.0,0,0,5,2.5,0.1,0.4,0
511,496,Dede Westbrook,JAX,27,NaN,2,0,1,1,100.0%,4,4.0,0,0,4,4.0,0.5,2.0,1
512,497,Antonio Williams,BUF,23,NaN,1,0,1,1,100.0%,20,20.0,0,1,20,20.0,1.0,20.0,0
513,498,Luke Willson,2TM,30,NaN,8,0,3,1,33.3%,12,12.0,0,0,12,4.0,0.1,1.5,0
514,499,T.J. Yeldon,BUF,27,NaN,3,0,4,1,25.0%,22,22.0,1,1,22,5.5,0.3,7.3,1

In [18]:
#We have 139 missing positions. We will fill those in again
wr2020.isnull().sum()

Rk          0
Player      0
Tm          0
Age         0
Pos       139
G           0
GS          0
Tgt         0
Rec         0
Ctch%       0
Yds         0
Y/R         0
TD          0
1D          0
Lng         0
Y/Tgt       0
R/G         0
Y/G         0
Fmb         0
dtype: int64

In [19]:
#Here we go again
wr2020.Pos[82] = 'RB'
wr2020.Pos[158] = 'RB'
wr2020.Pos[176] = 'RB'
wr2020.Pos[189] = 'RB'
wr2020.Pos[194] = 'RB'
wr2020.Pos[204] = 'WR'
wr2020.Pos[209] = 'WR'
wr2020.Pos[212] = 'RB'
wr2020.Pos[220] = 'WR'
wr2020.Pos[223] = 'RB'
wr2020.Pos[225] = 'RB'
wr2020.Pos[227] = 'WR'
wr2020.Pos[228] = 'WR'
wr2020.Pos[229] = 'WR'
wr2020.Pos[231] = 'RB'
wr2020.Pos[237] = 'WR'
wr2020.Pos[238] = 'RB'
wr2020.Pos[240] = 'WR'
wr2020.Pos[241] = 'RB'
wr2020.Pos[248] = 'RB'
wr2020.Pos[251] = 'RB'
wr2020.Pos[257] = 'WR'
wr2020.Pos[260] = 'WR'
wr2020.Pos[263] = 'RB'
wr2020.Pos[268] = 'WR'
wr2020.Pos[273] = 'WR'
wr2020.Pos[279] = 'RB'
wr2020.Pos[283] = 'RB'
wr2020.Pos[287] = 'TE'
wr2020.Pos[288] = 'RB'
wr2020.Pos[294] = 'RB'
wr2020.Pos[295] = 'WR'
wr2020.Pos[297] = 'TE'
wr2020.Pos[298] = 'RB'
wr2020.Pos[301] = 'WR'
wr2020.Pos[302] = 'WR'
wr2020.Pos[304] = 'RB'
wr2020.Pos[314] = 'RB'
wr2020.Pos[315] = 'RB'
wr2020.Pos[322] = 'RB'
wr2020.Pos[325] = 'TE'
wr2020.Pos[330] = 'RB'
wr2020.Pos[331] = 'RB'
wr2020.Pos[334] = 'RB'
wr2020.Pos[336] = 'RB'
wr2020.Pos[337] = 'WR'
wr2020.Pos[342] = 'WR'
wr2020.Pos[347] = 'WR'
wr2020.Pos[350] = 'RB'
wr2020.Pos[352] = 'WR'
wr2020.Pos[354] = 'WR'
wr2020.Pos[355] = 'RB'
wr2020.Pos[357] = 'RB'
wr2020.Pos[361] = 'RB'
wr2020.Pos[362] = 'WR'
wr2020.Pos[365] = 'WR'
wr2020.Pos[368] = 'RB'
wr2020.Pos[372] = 'RB'
wr2020.Pos[376] = 'RB'
wr2020.Pos[378] = 'RB'
wr2020.Pos[379] = 'WR'
wr2020.Pos[383] = 'RB'
wr2020.Pos[384] = 'RB'
wr2020.Pos[385] = 'RB'
wr2020.Pos[386] = 'WR'
wr2020.Pos[392] = 'WR'
wr2020.Pos[394] = 'WR'
wr2020.Pos[395] = 'WR'
wr2020.Pos[397] = 'WR'
wr2020.Pos[398] = 'WR'
wr2020.Pos[400] = 'RB'
wr2020.Pos[402] = 'WR'
wr2020.Pos[403] = 'RB'
wr2020.Pos[404] = 'WR'
wr2020.Pos[405] = 'WR'
wr2020.Pos[406] = 'WR'
wr2020.Pos[407] = 'WR'
wr2020.Pos[408] = 'TE'
wr2020.Pos[410] = 'TE'
wr2020.Pos[412] = 'RB'
wr2020.Pos[413] = 'TE'
wr2020.Pos[416] = 'RB'
wr2020.Pos[418] = 'WR'
wr2020.Pos[420] = 'TE'
wr2020.Pos[422] = 'TE'
wr2020.Pos[425] = 'RB'
wr2020.Pos[426] = 'RB'
wr2020.Pos[433] = 'FB'
wr2020.Pos[435] = 'RB'
wr2020.Pos[436] = 'RB'
wr2020.Pos[438] = 'WR'
wr2020.Pos[439] = 'WR'
wr2020.Pos[440] = 'TE'
wr2020.Pos[442] = 'RB'
wr2020.Pos[444] = 'TE'
wr2020.Pos[445] = 'RB'
wr2020.Pos[447] = 'WR'
wr2020.Pos[450] = 'RB'
wr2020.Pos[451] = 'FB'
wr2020.Pos[452] = 'TE'
wr2020.Pos[454] = 'TE'
wr2020.Pos[455] = 'WR'
wr2020.Pos[456] = 'RB'
wr2020.Pos[457] = 'TE'
wr2020.Pos[460] = 'WR'
wr2020.Pos[461] = 'TE'
wr2020.Pos[466] = 'RB'
wr2020.Pos[467] = 'RB'
wr2020.Pos[469] = 'FB'
wr2020.Pos[470] = 'WR'
wr2020.Pos[471] = 'TE'
wr2020.Pos[472] = 'RB'
wr2020.Pos[473] = 'WR'
wr2020.Pos[474] = 'RB'
wr2020.Pos[475] = 'RB'
wr2020.Pos[476] = 'RB'
wr2020.Pos[478] = 'WR'
wr2020.Pos[480] = 'WR'
wr2020.Pos[481] = 'RB'
wr2020.Pos[482] = 'WR'
wr2020.Pos[483] = 'WR'
wr2020.Pos[485] = 'WR'
wr2020.Pos[488] = 'FB'
wr2020.Pos[490] = 'WR'
wr2020.Pos[491] = 'TE'
wr2020.Pos[492] = 'CB'
wr2020.Pos[493] = 'RB'
wr2020.Pos[496] = 'WR'
wr2020.Pos[497] = 'RB'
wr2020.Pos[501] = 'WR'
wr2020.Pos[504] = 'RB'
wr2020.Pos[505] = 'TE'
wr2020.Pos[507] = 'LB'
wr2020.Pos[508] = 'RB'
wr2020.Pos[509] = 'RB'
wr2020.Pos[511] = 'WR'
wr2020.Pos[512] = 'RB'
wr2020.Pos[513] = 'TE'
wr2020.Pos[514] = 'RB'

In [20]:
#Time to check the missing values. Should have none
wr2020.isnull().sum()

Rk        0
Player    0
Tm        0
Age       0
Pos       0
G         0
GS        0
Tgt       0
Rec       0
Ctch%     0
Yds       0
Y/R       0
TD        0
1D        0
Lng       0
Y/Tgt     0
R/G       0
Y/G       0
Fmb       0
dtype: int64

In [21]:
#Lets replace some headers
wr2020.rename(columns={'TD': 'Touchdowns', 'Fmb':'Fumbles'}, inplace=True)

In [22]:
wr2020

,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Ctch%,Yds,Y/R,Touchdowns,1D,Lng,Y/Tgt,R/G,Y/G,Fumbles
0,1,Stefon Diggs*+,BUF,27,WR,16,15,166,127,76.5%,1535,12.1,8,73,55,9.2,7.9,95.9,0
1,2,Davante Adams*+,GNB,28,WR,14,14,149,115,77.2%,1374,11.9,18,73,56,9.2,8.2,98.1,1
2,3,DeAndre Hopkins*,ARI,28,WR,16,16,160,115,71.9%,1407,12.2,6,75,60,8.8,7.2,87.9,3
3,4,Darren Waller*,LVR,28,TE,16,15,145,107,73.8%,1196,11.2,9,69,38,8.2,6.7,74.8,2
4,5,Travis Kelce*+,KAN,31,TE,15,15,145,105,72.4%,1416,13.5,11,79,45,9.8,7.0,94.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,495,Trevon Wesco,NYJ,25,te,12,4,2,1,50.0%,5,5.0,0,0,5,2.5,0.1,0.4,0
511,496,Dede Westbrook,JAX,27,WR,2,0,1,1,100.0%,4,4.0,0,0,4,4.0,0.5,2.0,1
512,497,Antonio Williams,BUF,23,RB,1,0,1,1,100.0%,20,20.0,0,1,20,20.0,1.0,20.0,0
513,498,Luke Willson,2TM,30,TE,8,0,3,1,33.3%,12,12.0,0,0,12,4.0,0.1,1.5,0
514,499,T.J. Yeldon,BUF,27,RB,3,0,4,1,25.0%,22,22.0,1,1,22,5.5,0.3,7.3,1

In [23]:
rb2020.rename(columns={'TD': 'Touchdowns', 'Fmb':'Fumbles'}, inplace=True)

C:\Users\David\anaconda3\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [24]:
rb2020

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,Touchdowns,1D,Lng,Y/A,Y/G,Fumbles
0,1,Derrick Henry *+,TEN,26,RB,16,16,378,2027,17,98,94,5.4,126.7,3
1,2,Dalvin Cook*,MIN,25,RB,14,14,312,1557,16,91,70,5.0,111.2,5
2,3,Josh Jacobs*,LVR,22,RB,15,15,273,1065,12,61,28,3.9,71.0,2
3,4,David Montgomery,CHI,23,RB,15,14,247,1070,8,59,80,4.3,71.3,1
4,5,Ezekiel Elliott,DAL,25,RB,15,15,244,979,6,62,31,4.0,65.3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,368,Jonathan Williams,DET,26,RB,5,0,1,5,0,0,5,5.0,1.0,1
380,369,Mike Williams,LAC,26,WR,15,11,1,1,0,0,1,1.0,0.1,0
381,370,Javon Wims,CHI,26,WR,13,1,1,2,0,0,2,2.0,0.2,0
382,371,Olamide Zaccheaus,ATL,23,WR,11,2,1,0,0,0,0,0.0,0.0,0
383,372,Brandon Zylstra,CAR,27,WR,16,2,1,1,0,0,1,1.0,0.1,0

In [26]:
rb2020[rb2020.Tm=='PHI']

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,Touchdowns,1D,Lng,Y/A,Y/G,Fumbles
20,21,Miles Sanders,PHI,23,RB,12,11,164,867,6,39,82,5.3,72.3,4
68,67,Boston Scott,PHI,25,RB,16,4,80,374,1,16,56,4.7,23.4,2
136,133,Corey Clement,PHI,26,RB,15,0,21,75,1,3,7,3.6,5.0,0
223,217,Jason Huntley,PHI,22,RB,5,0,5,19,0,1,10,3.8,3.8,0
240,234,Jalen Reagor,PHI,21,WR,11,11,4,26,0,2,19,6.5,2.4,2
302,294,Greg Ward,PHI,25,WR,16,10,2,-4,0,0,2,-2.0,-0.3,2
331,322,John Hightower,PHI,24,WR,13,4,1,1,0,0,1,1.0,0.1,0
337,328,DeSean Jackson,PHI,34,WR,5,5,1,12,0,1,12,12.0,2.4,0
342,332,Adrian Killins,PHI,22,RB,1,0,1,-12,0,0,-12,-12.0,-12.0,0

In [31]:
rb2020[rb2020.Tm=='SFO']

,Rk,Player,Tm,Age,Pos,G,GS,Att,Yds,Touchdowns,1D,Lng,Y/A,Y/G,Fumbles
37,37,Jeff Wilson,SFO,25,RB,12,3,126,600,7,31,34,4.8,50.0,2
47,47,Raheem Mostert,SFO,28,RB,8,8,104,521,2,22,80,5.0,65.1,1
67,66,Jerick McKinnon,SFO,28,RB,16,4,81,319,5,16,55,3.9,19.9,0
101,99,Jamycal Hasty,SFO,24,RB,8,0,39,148,1,7,20,3.8,18.5,1
125,122,Tevin Coleman,SFO,27,RB,8,1,28,53,0,3,12,1.9,6.6,0
146,143,Kyle Juszczyk*,SFO,29,FB,16,15,17,64,2,12,10,3.8,4.0,1
187,182,Deebo Samuel,SFO,24,WR,7,5,8,26,0,1,10,3.3,3.7,0
199,194,Brandon Aiyuk,SFO,22,WR,12,11,6,77,2,3,38,12.8,6.4,0
287,279,George Kittle,SFO,27,TE,8,8,2,17,0,1,9,8.5,2.1,0
376,365,Austin Walter,SFO,24,RB,4,0,1,3,0,0,3,3.0,0.8,0

array(['TEN', 'MIN', 'LVR', 'CHI', 'DAL', 'JAX', 'ARI', 'IND', 'DEN',
       'GNB', 'CLE', 'ATL', 'TAM', 'NYJ', 'NOR', 'KAN', 'WAS', 'PIT',
       'CAR', 'PHI', 'DET', 'BUF', 'NYG', 'HOU', 'LAR', 'BAL', 'MIA',
       'SEA', 'NWE', 'SFO', 'CIN', 'LAC', '2TM'], dtype=object)